/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(calcPhaseDiff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0a319d642c249e0d5f4a4d85d809f8da)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/etreesModule/calcPhaseDiff.h>
// pydoc.h is automatically generated in the build directory
#include <calcPhaseDiff_pydoc.h>

void bind_calcPhaseDiff(py::module& m)
{

    using calcPhaseDiff    = gr::etreesModule::calcPhaseDiff;


    py::class_<calcPhaseDiff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<calcPhaseDiff>>(m, "calcPhaseDiff", D(calcPhaseDiff))

        .def(py::init(&calcPhaseDiff::make),
           D(calcPhaseDiff,make)
        )
        



        ;




}








