/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(moveTag.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0305ecfa2d8cdbdb130342107539a739)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/etreesModule/moveTag.h>
// pydoc.h is automatically generated in the build directory
#include <moveTag_pydoc.h>

void bind_moveTag(py::module& m)
{

    using moveTag    = gr::etreesModule::moveTag;


    py::class_<moveTag, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<moveTag>>(m, "moveTag", D(moveTag))

        .def(py::init(&moveTag::make),
           D(moveTag,make)
        )
        



        ;




}








