/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rangeDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(093daad9b805d4978fd1da023bc06570)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/etreesModule/rangeDetector.h>
// pydoc.h is automatically generated in the build directory
#include <rangeDetector_pydoc.h>

void bind_rangeDetector(py::module& m)
{

    using rangeDetector    = gr::etreesModule::rangeDetector;


    py::class_<rangeDetector, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rangeDetector>>(m, "rangeDetector", D(rangeDetector))

        .def(py::init(&rangeDetector::make),
           D(rangeDetector,make)
        )
        



        ;




}








